[package]
name              = "magic-formatter"
version.workspace = true
edition.workspace = true

[[bin]]
name = "magic-formatter"
path = "src/main.rs"

[dependencies]
magic-core        = { workspace = true }
lang-rust         = { workspace = true }
lang-swift        = { workspace = true }
lang-toml         = { workspace = true }
lang-shell        = { workspace = true }
lang-python       = { workspace = true }
tree-sitter       = { workspace = true }
lsp-server        = { workspace = true }
lsp-types         = { workspace = true }
serde_json        = { workspace = true }
url               = { workspace = true }
ignore            = { workspace = true }
crossbeam-channel = "0.5"
